apiVersion: v1
kind: Secret
metadata:
  name: cloudflux-secrets
  namespace: cloudflux
type: Opaque
stringData:
  # AWS Credentials
  AWS_ACCESS_KEY_ID: "AKIAXE2C72SQWJNMFTC2"
  AWS_SECRET_ACCESS_KEY: "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"
  AWS_REGION: "us-east-1"
  AWS_S3_BUCKET: "cloudflux-demo-bucket"
  
  # Azure Credentials
  AZURE_STORAGE_ACCOUNT_NAME: "cloudfluxstorage123"
  AZURE_STORAGE_ACCOUNT_KEY: "NZYB7FxfO05A3DwTa4UE84nymRcHvD2pxGGmrmJziihDyEG912gqWLNCA+CumReWcjLxNseXqy+y+AStoI8GIA=="
  AZURE_CONTAINER_NAME: "cloudflux-container"
  
  # GCP Credentials
  GCP_PROJECT_ID: "robotic-jet-477613-e9"
  GCP_BUCKET_NAME: "cloudflux-gcp-bucket-477613"
  
  # JWT Secret
  JWT_SECRET_KEY: "cloudflux-production-secret-key-2025"
  
  # Database
  DATABASE_URL: "postgresql://cloudflux:cloudflux123@postgres:5432/cloudflux"
